export enum ScreenNames {
  WELCOME = 'Welcome',
  SIGN_IN = 'SignIn',
  SIGN_UP = 'SignUp',
  FORGOT_PASSWORD = 'ForgotPassword',
  CREATE_NEW_PASSWORD = 'CreateNewPassword',
  MAGIC_URL_VERIFY = 'MagicURLVerify',
  PERMISSION = 'Permission',
  PURPOSE = 'Purpose',
  NICKNAME = 'Nickname',
  INVITE = 'Invite',
  INVITE_SEND = 'InviteSend',
  SUBSCRIPTION = 'Subscription',
  HOME_TABS = 'HomeTabs',
  PROFILE = 'Profile',
  SETTINGS = 'Settings',
  NOT_FOUND = 'NotFound',
  HOME = 'Home',
  FORTY_DAY = 'FortyDay',
  BOOKMARK = 'Bookmark',
  TEMPTATION_DETAILS = 'TemptationDetails',
  TRANSCRIPT = 'Transcript',
  PRIVACY_POLICY = 'PrivacyPolicy',
  TERMS_CONDITIONS = 'TermsConditions',
  HELP_SUPPORT = 'HelpSupport',
  MANAGE_INVITES = 'ManageInvites',
}
